### PR TITLE
Updated MineTweaker Recipe Maker to 1.12.2.

### PR DESCRIPTION
**Pull request by HaydenBelanger**
Updated for myself this morning but I thought you might want me to merge in.

### CODE REVIEW

**Comment by dries007** [comment]
I don't have time to test at all, so I hope you did :)

**Comment by HaydenBelanger** [comment]
Tested and everything worked as it did in 1.11.

**Comment by dries007** [comment]
I uploaded a build to CurseForge, which was just approved. Thanks btw.

Tip for next time you'd like to port something: It's not a good idea to just nuke a big part of the build.gradle file, I had to fix it so it includes the MC version in the filename.

I presume the automatic reload doesn't work anymore so that's why it got removed? (I figured that would be the case eventually.)

**Comment by HaydenBelanger** [comment]
Auto reload was giving me crashes before I sent you the working code, so I just took it out. Sorry about the gradlew thing, still 100% not super great with production-level conventions and such, mostly just develop for personal stuff.

**Comment by Claycorp** [comment]
From what I last heard (like 4-6 months ago) the reloading in-game was removed in 1.12+ Mine/Craft/WhateverTweaker. I would assume that never changed. @dries007

**Comment by Codingale** [comment]
also didn't the API change?:

https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/#add-recipes you need a name now right?

**Comment by Claycorp** [comment]
No,
"name is a string and needs to be unique but is also optional"
People have been using this for months now. If it was to have broke there would be 50 issues about how it didn't work anymore.

**Pull request merged**
